# Generated by Django 5.0.1 on 2024-02-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacteduser',
            old_name='website',
            new_name='subject',
        ),
    ]
