# Generated by Django 5.0.1 on 2024-02-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniapp', '0002_rename_website_contacteduser_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
